TARGET ?= main
CC     ?= gcc

INCLUDE_DIR ?= include
LIB_DIR     ?= lib

CFLAGS  = -I$(INCLUDE_DIR)
LDFLAGS = -L$(LIB_DIR) -lraylib -lgdi32 -lwinmm

.PHONY: all run clean

all: $(TARGET).exe

$(TARGET).exe: $(TARGET).c
    @echo Compilando $@
    @$(CC) -o $@ $< $(CFLAGS) $(LDFLAGS)
    @echo Pronto!

run: all
    @echo Executando...
    @./$(TARGET).exe

clean:
    @rm -f $(TARGET).exe
